# .github/workflows/ci-cd.yml

name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Ou a versão que você usa
        cache: 'npm'

    - name: Instalar dependências
      run: npm ci # 'ci' é geralmente melhor para CI/CD do que 'install'

    - name: Executar testes com Jest

      run: npm test
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        TEST_AUTH_TOKEN: ${{ secrets.TEST_AUTH_TOKEN }}
        AUTH_SECRET: ${{ secrets.AUTH_SECRET }}